### ISSUE TITLE
Unity Editor interface for creating feature filters

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-unity#20]
Rather than encoding filters in a custom text format, we can create a specialized GUI for visualizing and editing feature filters and de/serialize them using Unity's built-in mechanisms.

**Comment by karimnaaji** [comment]
Some ideas for improvements following https://github.com/tangrams/tangram-unity/pull/42:
- Filter mathers GUI interface
- Serialization of filters as generic assets
- Maybe support for nested filters

**Comment by matteblair** [comment]
I think we're going to need to refactor some of our data model and GUI to accommodate nested, hierarchical filters. There are good reasons that Tangram uses a filter hierarchy and if we expect to enable any non-trivial styling then we should leverage the lessons learned from Tangram.

It would be certainly be possible to encode complex styling in a flat, ordered list of filters, and in some ways this would be simpler to reason about. From an authoring perspective however, a hierarchy saves a lot of repetition and makes refactors much easier.
