### ISSUE TITLE
Incorrect buildings in Bratislava

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-unity#80]
Hi, this plugin looks very good :). I have tried to download Bratislava and some buildings are ok as 3D objects but most of them does not show as 3D objects but they are flat. I am attaching screenshot. Also you can see there coordinates, so you can try to reproduce it.

![bratislava](https://user-images.githubusercontent.com/2378743/32398625-b9114302-c0f0-11e7-8e80-51c17f173bf3.png)

**Comment by nvkelso** [comment]
Is a default extrusion (probably 3 to 5 meters) applied to buildings
without a height?

**Comment by matteblair** [comment]
Hey @rwrx thanks for the feedback! Please excuse our mess, this is still heavy development 😄 

Extruded polygons currently use the `MaxHeight` option if it's greater than zero, otherwise it uses the `height` value from the feature (or zero if absent).

This will definitely change in the future. For now you could make two building layers, one with a filter for buildings without `height` that applies a `MaxHeight` of 3 or 5.

**Comment by rwrx** [comment]
Thank you for your response. I haven't looked into actual code yet. Thanks for the solution I will try somehow add your solution, but as of now I don't know how, but I will try. If I will have some problems I will answer again :). Thank you.

**Comment by rwrx** [comment]
Will this project be at least to some degree maintained after shutting down Mapzen? Also I have tried to resolve this with latest code, but now it seems that setting this filter is not working for buildings without height. I tried to do it as in November version of code, but now it does not extrude buildings. Was this functionality changed or removed? Thank you.

**Comment by matteblair** [comment]
Not sure how much work this repo will receive in the future - it probably depends on how much attention it gets!

The asset format for map styles was almost completely re-written in [this PR](https://github.com/tangrams/tangram-unity/pull/82) so if you are using a style from before that it's best to just re-make it from scratch.

**Comment by rwrx** [comment]
Thank you for your fast response. I have decided to use this project as a basis for my game, but I am happy with funcionality which it currently offers.

I have used default ExampleMapStyle which has new style form, and added there a new filter to try to match buildings with zero or none height, but it didn't work.

**Comment by rwrx** [comment]
Thank you. I have resolved this.
