### ISSUE TITLE
TileIO Error: HTTP Error with errorcode: 403

### ISSUE THREAD

**Issue by jonijoba** [tangrams/tangram-unity#91]
With unity 2017.2.0.f3

25 same errors:

TileIO Error: HTTP Error with errorcode: 403
UnityEngine.Debug:Log(Object)
Mapzen.<DownloadTilesAsync>c__AnonStorey2:<>m__0(Response) (at Assets/RegionMap.cs:119)
Mapzen.Unity.<FetchNetworkData>c__Iterator0:MoveNext() (at Assets/Mapzen/Unity/IO.cs:65)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by matteblair** [comment]
Are you missing an API key? A valid API key is needed for the tile requests to complete.

**Comment by Gonzalo15** [comment]
To solve this error you should change 
var uri = new Uri(string.Format("https://tile.mapzen.com/mapzen/vector/v1/all/{0}/{1}/{2}.mvt?api_key={3}",

by 

var uri = new Uri(string.Format("https://tile.nextzen.org/tilezen/vector/v1/all/{0}/{1}/{2}.mvt?api_key={3}",           

at Region Map.cs line 103.
As it is said above and in other Issues, Mapzen is off but thanks to Nextzen is quite eassy to transform the progect to its services.
https://developers.nextzen.org/about.html

**Comment by matteblair** [comment]
Thanks for reminding me about this - fixed this URL and a few others https://github.com/tangrams/tangram-unity/commit/2f57ffa8b7ca426f6d8f444484547b27d9d24955
